invoice_app/urls.py
from django.urls import path
from .views import (
    InvoiceListView,
    InvoiceDetailView,
    InvoiceCreateView,
    InvoiceUpdateView,
    InvoiceDeleteView,
    InvoicePDFView,
    
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientUpdateView,
    ClientDeleteView,
)

app_name='invoice_app'
urlpatterns = [
    path("", InvoiceListView.as_view(), name="invoice-list"),
    path("<int:pk>/", InvoiceDetailView.as_view(), name="invoice-detail"),
    path("create/", InvoiceCreateView.as_view(), name="invoice-create"),
    path("<int:pk>/update/", InvoiceUpdateView.as_view(), name="invoice-update"),
    path("<int:pk>/delete/", InvoiceDeleteView.as_view(), name="invoice-delete"),
    path('invoice/<int:pk>/pdf/', InvoicePDFView.as_view(), name='invoice-pdf'),

    path("clients/", ClientListView.as_view(), name="client-list"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client-detail"),
    path("clients/create/", ClientCreateView.as_view(), name="client-create"),
    path("clients/<int:pk>/update/", ClientUpdateView.as_view(), name="client-update"),
    path("clients/<int:pk>/delete/", ClientDeleteView.as_view(), name="client-delete"),
]

invoice_project/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
from invoice_app.api import api


urlpatterns = [
    path('', include('invoice_app.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),
    path("api/v1/", api.urls),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'invoice_app/static'),
        }
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice_app/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from .utils import upload_logo, upload_sign, validate_phone_number
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from .storage import OverwriteStorage


class InvoiceOwner(AbstractUser):
    is_onboarded = models.BooleanField(default=False)
    address = models.TextField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=15)
    phone_2 = models.CharField(max_length=15, blank=True, null=True)
    ntn_number = models.CharField(max_length=15, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    bank = models.CharField(max_length=55, blank=True, null=True)
    account_title = models.CharField(max_length=24, blank=True, null=True)
    iban = models.CharField(max_length=34, blank=True, null=True)
    logo = ProcessedImageField(
        upload_to=upload_logo,
        storage=OverwriteStorage(),
        processors=[ResizeToFill(500, 500)],
        format='PNG',
        options={'quality': 90},
        null=True,
        blank=True,
    )
    signature = ProcessedImageField(
        upload_to=upload_sign,
        storage=OverwriteStorage(),
        processors=[ResizeToFill(577, 432)],
        format='PNG',
        options={'quality': 90},
        null=True,
        blank=True,
    )

    username = None
    first_name = None
    last_name = None

    email = models.EmailField(_("email address"), unique=True)
    name = models.CharField(max_length=255)

    USERNAME_FIELD = "email"
    FIRST_NAME_FIELD = "name"
    REQUIRED_FIELDS = ['name', 'address', 'phone']

    objects = CustomUserManager()

    class Meta:
        verbose_name = "Invoice Owner"

    def clean(self):
        super().clean()

        validate_phone_number(self.phone)

        if self.phone_2:
            validate_phone_number(self.phone_2)

        if self.ntn_number and not (7 <= len(self.ntn_number) <= 15):
            raise ValidationError(_("NTN number must be 7 to 15 characters long."))
    
    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField(max_length=255, null=True, blank=True)
    ntn_number = models.CharField(max_length=15, null=True, blank=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    invoice_owner = models.ForeignKey(InvoiceOwner, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-updated_at',)

    def clean(self):
        if self.phone:
            validate_phone_number(self.phone)

        if self.ntn_number and not (7 <= len(self.ntn_number) <= 15):
            raise ValidationError("NTN number must be 7 to 15 characters long.")

    def __str__(self):
        return self.name


class Invoice(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name="invoices")
    reference_number = models.CharField(max_length=14, editable=False)
    tax_percentage = models.DecimalField(
        max_digits=5, blank=True, null=True, decimal_places=3, validators=[MinValueValidator(0)]
    )
    total_price = models.DecimalField(max_digits=16, default=0, decimal_places=3, editable=False)
    tax = models.DecimalField(max_digits=16, default=0, decimal_places=3, editable=False)
    grand_total = models.DecimalField(max_digits=16, default=0, decimal_places=3, editable=False)
    date = models.DateField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_taxed = models.BooleanField(default=False)
    is_quotation = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)
    transit_charges = models.DecimalField(max_digits=16, default=0, decimal_places=3, null=True, blank=True)

    def clean(self):
        """Validate tax_percentage."""
        if self.tax_percentage and not (0 <= self.tax_percentage <= 100):
            raise ValidationError(_("Tax percentage must be between 0 and 100."))

    def calculate_totals(self):
        """Calculate total_price, tax, and grand_total."""
        self.total_price = sum(item.total_price for item in self.items.all())
        
        if self.transit_charges:
            self.total_price += self.transit_charges
 
        self.tax = self.total_price * (self.tax_percentage / 100) if self.tax_percentage else 0
        self.grand_total = self.total_price + self.tax

    @staticmethod
    def get_next_reference_number(last_invoice=None, is_quotation=False):
        """Generate the next reference number in sequence."""
        
        if last_invoice:
            last_number = int(last_invoice.reference_number.split('-')[1])
            next_number = last_number + 1
        else:
            next_number = 1
        
        if is_quotation:
            return f"Q_SAE-{next_number:04d}"  # Quotation reference number (Q_SAE-xxxx)
        else:
            return f"I_SAE-{next_number:04d}"  # Invoice reference number (I_SAE-xxxx)

    def save(self, *args, **kwargs):
        """Override save to set the reference number before saving, and handle is_quotation changes."""
        
        is_quotation_changed = False
        
        if self.pk:
            old_invoice = Invoice.objects.get(pk=self.pk, client__invoice_owner=self.client.invoice_owner.pk)
            is_quotation_changed = old_invoice.is_quotation != self.is_quotation

        if not self.reference_number or is_quotation_changed:
            if self.is_quotation:
                last_quotation = Invoice.objects.filter(is_quotation=True, client__invoice_owner=self.client.invoice_owner.pk).order_by('-id').first()
                self.reference_number = Invoice.get_next_reference_number(last_quotation, is_quotation=True)
            else:
                last_invoice = Invoice.objects.filter(is_quotation=False, client__invoice_owner=self.client.invoice_owner.pk).order_by('-id').first()
                self.reference_number = Invoice.get_next_reference_number(last_invoice, is_quotation=False)
        
        super().save(*args, **kwargs)
        self.calculate_totals()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Invoice {self.reference_number}"


class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name="items")
    unit = models.CharField(max_length=55)
    description = models.TextField(null=True, blank=True)
    name = models.CharField(max_length=255)
    quantity = models.DecimalField(max_digits=16, decimal_places=3, validators=[MinValueValidator(0)])
    unit_price = models.DecimalField(max_digits=16, decimal_places=3, validators=[MinValueValidator(0)])
    total_price = models.DecimalField(max_digits=16, decimal_places=3, editable=False)

    def save(self, *args, **kwargs):
        """Calculate total_price based on quantity and unit_price."""
        self.total_price = self.quantity * self.unit_price
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} - {self.quantity} x {self.unit_price}"

invoice_app/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .widgets import NoTrailingZeroNumberInput
from .models import Invoice, InvoiceOwner, InvoiceItem, Client

class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ['client', 'is_paid', 'is_quotation', 'is_taxed', 'tax_percentage', 'transit_charges', 'date', 'notes']
        widgets = {
            'transit_charges': NoTrailingZeroNumberInput(attrs={
                'min': '0',
                'step': '0.001',  # Use 0.01 for decimal precision
                'placeholder': 'Enter transit charges (if any)',
            }),
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'placeholder': 'Select a date', 'type': 'date'}
            ),
            'notes': forms.Textarea(attrs={
                'rows': 3,
                'placeholder': 'Enter additional notes',
            }),
        }
    is_paid = forms.BooleanField(label='Payment', required=False)
    is_taxed = forms.BooleanField(label='Tax Included', required=False)
    is_quotation = forms.BooleanField(label='Quotation', required=False)
    tax_percentage = forms.DecimalField(
        required=False,
        initial=0,
        max_digits=5,
        decimal_places=3,
        widget=NoTrailingZeroNumberInput(attrs={
            'min': '0',
            'max': '99999',
            'step': '0.001',
            'placeholder': 'Enter tax percentage (without "%")',
        })
    )

    client = forms.ModelChoiceField(queryset=Client.objects.all(), empty_label="Select Client or Create New", required=True, widget=forms.Select(attrs={'autofocus': True}))

    def clean(self):
        cleaned_data = super().clean()

        client = cleaned_data.get('client')
        if client:
            cleaned_data['invoice_owner'] = client.invoice_owner

        return cleaned_data

class InvoiceOwnerCreationForm(UserCreationForm):
    class Meta:
        model = InvoiceOwner
        fields = ["email", "ntn_number", "name", 'phone', 'phone_2', 'address', 'bank', 'iban', 'account_title', 'logo', 'signature',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['ntn_number'].required = True
        self.fields['phone'].required = True
        self.fields['bank'].required = True
        self.fields['address'].required = True
        self.fields['iban'].required = True
        self.fields['account_title'].required = True
        self.fields['logo'].required = True
        self.fields['signature'].required = True
  

class InvoiceOwnerChangeForm(UserChangeForm):
    class Meta:
        model = InvoiceOwner
        fields = ["email", "ntn_number", "name", 'phone', 'phone_2', 'address', 'bank', 'iban', 'account_title', 'logo', 'signature',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['ntn_number'].required = True
        self.fields['phone'].required = True
        self.fields['bank'].required = True
        self.fields['address'].required = True
        self.fields['iban'].required = True
        self.fields['account_title'].required = True
        self.fields['logo'].required = True
        self.fields['signature'].required = True


class InvoiceItemForm(forms.ModelForm):
    class Meta:
        model = InvoiceItem
        fields = ['name', 'description', 'quantity', 'unit', 'unit_price',]
        widgets = {
            'quantity': NoTrailingZeroNumberInput(attrs={
                'min': '0',
                'max': '999999',
                'step': '0.001',
                'placeholder': 'Enter item quantity',
            }),
            'unit_price': NoTrailingZeroNumberInput(attrs={
                'min': '0',
                'step': '0.001',  # Use 0.01 for decimal precision
                'placeholder': 'Enter item price',
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'Enter item name',
                'autofocus': 'autofocus',
                'autocomplete': 'off',
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'Enter item description',
                'rows': 3,
            }),
            'unit': forms.TextInput(attrs={
                'placeholder': 'Enter quantity unit i.e pc(s), box(es), unit(s)',
            })
        }


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'phone', 'address', 'ntn_number',]
        widgets = {
            'phone': forms.TextInput(attrs={
                'placeholder': 'Enter client phone number',
                'autocomplete': 'off',
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'Enter client name',
                'autofocus': 'autofocus',
                'autocomplete': 'off',
            }),
            'address': forms.TextInput(attrs={
                'placeholder': 'Enter client address',
                'rows': 2,
                'autocomplete': 'off',
            }),
            'ntn_number': forms.TextInput(attrs={
                'placeholder': 'Enter client ntn number',
                'autocomplete': 'off',
            })
        }


InvoiceItemFormSet = forms.inlineformset_factory(
    Invoice, InvoiceItem, form=InvoiceItemForm, extra=1, can_delete=True
)

invoice_app/templates/invoice_app/client/delete.html
{% extends "base_bootstrap.html" %}
{% block navbar %}<p class="border-3 border-top border-warning"></p>{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="card shadow-sm border-danger mx-auto" style="max-width: 500px;">
    <div class="card-body">
      <h3 class="card-title text-center text-danger mb-4">Delete Client</h3>
      <p class="text-center mb-4">Are you sure you want to delete the client: <strong>{{ client }}</strong>?</p>
      <form method="POST">
        {% csrf_token %}
        <div class="d-flex justify-content-around">
          <button type="submit" class="btn btn-danger btn-sm" value="Yes, delete." autofocus>
            Yes, delete <i class="fa fa-trash"></i>
          </button>
          <button type="button" class="btn btn-outline-secondary btn-sm" onclick="window.location.href='{% url 'invoice_app:client-list' %}'; return false;">
            Cancel <i class="fa fa-times"></i>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

invoice_app/templates/invoice_app/client/detail.html
{% extends "base_bootstrap.html" %}
{% load humanize %}
{% block navbar %}<p class="border-3 border-top border-warning"></p>{% endblock %}
{% block title %}Client Detail{% endblock %}

{% block content %}
<div class="container d-flex flex-column">
    <h2 class="fw-bold text-wrap mb-2 text-light">{{ client.name }}</h2>
    <p class="mb-0"><strong>Phone:</strong> <small>{{ client.phone }}</small></p>
    <p class="mb-0"><strong>Address:</strong> <small>{{ client.address }}</small></p>
    <p class="mb-0"><strong>Created at:</strong> {{ client.created_at }}</p>
    <p><strong>Updated at:</strong> {{ client.updated_at }}</p>
    <div class="d-flex justify-content-between mt-2 mb-4">
        <a class="btn flex-grow-1 btn-outline-primary btn-sm me-1" href="{% url 'invoice_app:client-update' client.pk %}">
        Edit <i class="fa fa-pencil"></i></a>
        <a href="{% url 'invoice_app:client-list' %}" class="btn btn-outline-secondary fw-bold btn me-1 btn-sm">
          Client List <i class="fa fa-bars"></i>
        </a>
        <a class="btn btn-outline-danger btn-sm" href="{% url 'invoice_app:client-delete' client.pk %}">
          Delete <i class="fa fa-trash"></i></a>
    </div>
</div>
{% endblock %}

invoice_app/templates/invoice_app/client/form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ form.instance.pk|yesno:"Edit,Create" }} Client{% endblock %}
{% block navbar %}<p class="border-3 border-top border-warning"></p>{% endblock %}
{% block content %}
<div class="container">
    <h1>{{ form.instance.pk|yesno:"Edit,Create" }} Client</h1>
    <form method="post" id="theForm">
        {% csrf_token %}
        <div class="card mb-4">
            <div class="card-body">
                {{ form|crispy }}
            </div>
        </div>

        <div class="mt-2">
            <button id="save-button" type="submit" class="btn btn-outline-primary btn-sm">
                Save <i class="fa fa-save"></i>
            </button>
            <button id="cancel-button" type="button" class="btn btn-outline-secondary btn-sm" value="Cancel" onclick="window.location.href='{% url 'invoice_app:client-list' %}';return false;">Cancel <i class="fa fa-times"></i></button>
            </button>
        </div>
    </form>
</div>
<script>
    document.querySelector('#save-button').addEventListener('click', function(event) {
        event.preventDefault();
        document.getElementById('theForm').submit();
        if (window.opener) {
            window.opener.location.reload();
        }
    });

    document.getElementById('cancel-button').addEventListener('click', function(event) {
        if (window.opener) {
            window.opener.location.reload();
        }
        window.close();
    });
</script>
{% endblock %}

invoice_app/templates/invoice_app/client/list.html
{% extends "base_bootstrap.html" %}
{% block title %}Client List{% endblock %}
{% block navbar %}<p class="border-3 border-top border-warning"></p>{% endblock %}
{% block content %}
<h1 class="fw-bold text-center my-3">Client List</h1>

<!-- Search Form -->
<div class="mb-3">
  <form>
    <div class="d-flex align-items-center">
      <input class="form-control form-control-sm border me-2" type="text" placeholder="Search Client (name, ntn number, phone, or address)" name="search"
      {% if search %} value="{{ search }}" {% endif %} style="outline: none; box-shadow: none;">
      <button class="btn btn-outline-light btn-sm" type="submit"><i class="fa fa-search"></i></button>
      <a class="ms-2 btn btn-outline-secondary btn-sm" href="{% url 'invoice_app:client-list' %}"><i class="fa fa-undo"></i></a>
    </div>
  </form>
</div>

<!-- User Action Buttons -->
<div class="d-flex justify-content-between mt-2 mb-4">
  <!-- Create New Invoice Button -->
  <a href="{% url 'invoice_app:client-create' %}" class="btn btn-outline-success fw-bold flex-grow-1 btn me-1 btn-sm">
    Create New Client <i class="fa fa-plus"></i>
  </a>

  <!-- Dropdown -->
  <div class="btn-group">
    <button type="button" class="btn btn-outline-primary btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      Options
    </button>
    <ul class="dropdown-menu">
      <li>
        <a class="dropdown-item" href="{% url 'invoice_app:invoice-list' %}">Invoices
          <i class="ms-1 fa fa-bars"></i> 
        </a>
      </li>
      <li>
        <a class="dropdown-item" href="{% url 'logout' %}?next={% url 'invoice_app:invoice-list' %}">Logout
          <i class="ms-1 fa fa-sign-out"></i> 
        </a>
      </li>
    </ul>
  </div>
</div>

<!-- Client List -->
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 g-4">
  {% for client in client_list %}
    <div class="col">
      <div class="card shadow-lg border-0 bg-dark text-light">
        <div class="card-body">
          <h5 class="card-title">{{ client.name }}</h5>
          <p class="card-text text-muted mb-0">
            <small><strong>Ntn Number:</strong> {{ client.ntn_number }}</small>
          </p>         
          {% if client.phone %}
            <p class="card-text text-muted">
              <small>
                <strong>Phone:</strong> {{ client.phone }}
              </small>
            </p>
          {% endif %}

          <div class="d-flex gap-2 mt-3">
            <a href="{% url 'invoice_app:client-detail' client.pk %}" class="btn btn-outline-success btn-sm w-100">
              View Details <i class="fa fa-info-circle"></i>
            </a>
          </div>
          <div class="d-flex gap-2 mt-2">
            <a href="{% url 'invoice_app:client-delete' client.pk %}" class="btn btn-outline-danger btn-sm w-100">
              Delete <i class="fa fa-trash"></i>
            </a>
            <a href="{% url 'invoice_app:client-update' client.pk %}" class="btn btn-outline-secondary btn-sm w-100">
              Edit <i class="fa fa-pencil"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

<!-- Display this message only when there are no clients -->
{% if not client_list %}
  <div class="row">
    <div class="col-12 mt-4 text-center text-danger fw-bold">
      <p>No clients found.</p>
    </div>
  </div>
{% endif %}
</div>
{% endblock %}